# Generated by Django 4.1.1 on 2022-11-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_playlist_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spotifyLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
